#!/bin/zsh

# A script to check and fetch the last chapters of some scans I follow.
# The 'tag update' part works badly.

function actual_nb () {
	ls ~/scans/"$1" | \
		perl -ne 'print "$_\n" for /(\d+)[^\d]*$/' | \
		tail -n 1
}

function err () {
	echo "Error occured :("
	exit 1
}

scans

# get number of the last chapter out
bl_out="$(linkgrab bll | head -n 1)" || err

echo "Last Blood Lad chap is $bl_out"

# get number of the last downloaded chapter
bl_dl="$(actual_nb 'Blood Lad')" || err

# create the arguments for each chap to download
args=
if [ "$bl_out" != "" ] && [ "$bl_out" -gt "$bl_dl" ]; then
	args+=" bl{$(($bl_dl + 1))..$bl_out}"
	echo Blood Lad, new chaps: {$(($bl_dl + 1))..$bl_out}
fi

# download with linkgrab if needed
if [ -n "$args" ]; then
	echo "Downloading…"
	eval linkgrab ${args}
else
	echo "No new chapters."
fi
