set nocompatible              " be iMproved
filetype off                  " required!

" manage bundles with Vundle
"
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" required!
Bundle 'gmarik/vundle'

" sensible default config
Bundle 'tpope/vim-sensible'

" amalgamation of crap for editing runtime files
Bundle 'tpope/vim-scriptease'

" asynchronous build and test dispatcher
Bundle 'tpope/vim-dispatch'

" continuously updated session files
Bundle 'tpope/vim-obsession'

" unicode character metadata
Bundle 'tpope/vim-characterize'

" helpers for UNIX
Bundle 'tpope/vim-eunuch'

" comment stuff out
Bundle 'tpope/vim-commentary'

" easily search for, substitute, and abbreviate multiple variants of a word
Bundle 'tpope/vim-abolish'

" enable repeating supported plugin maps with .
Bundle 'tpope/vim-repeat'

" experimental enhancement of f and t keys
Bundle 'tpope/vim-flatfoot'

" quoting/parenthesizing made simple
Bundle 'tpope/vim-surround'

" fancy status line
Bundle 'bling/vim-airline'

" Emacs-style yank ring
Bundle 'vim-scripts/YankRing.vim'

" git diff in the sign column
Bundle 'airblade/vim-gitgutter'

" three-way merge helper
Bundle 'sjl/splice.vim'

" perform all insert mode completions with Tab
Bundle 'ervandew/supertab'

" Sublime Text style multiple selections
Bundle 'terryma/vim-multiple-cursors'

" plugin that displays tags in a window
Bundle 'majutsushi/tagbar'

" syntax for Rockbox theme files
Bundle 'vim-scripts/wps.vim'

" my junk
Bundle 'PotatoesMaster/vim-colors-harold'
Bundle 'PotatoesMaster/vim-movelines'
Bundle 'PotatoesMaster/i3-vim-syntax'

filetype plugin indent on     " required!

syntax on

if filereadable(expand('~/.vimrc.local'))
  source ~/.vimrc.local
endif
