#!/bin/sh

# Script for i3bar.
# Launch or restart conky.

killall conky

# Outputs to stdout for i3bar to display it.
echo '{"version": 1}[[],'
cd ~/.i3

# sometimes conky crashes, rerun it if it happens
while true; do
    nice -n 19 conky -c conky.lua
    sleep 1 # just in case
done
