#!/usr/bin/python

" Add 1px border to transparent images.
" Can be helpful for pixel-art drawing.

from sys import argv
from PIL import Image

fname = argv[1]
img = Image.open(fname)

w, h = img.size
for y in range(h):
    for x in range(w):
        b = img.getpixel((x, y))

        if b[3] == 255:
            if y > 0 and img.getpixel((x, y - 1))[3] == 0 \
                or y < h-1 and img.getpixel((x, y + 1))[3] == 0 \
                or x > 0 and img.getpixel((x - 1, y))[3] == 0 \
                or x < w-1 and img.getpixel((x + 1, y))[3] == 0:
                img.putpixel((x, y), (37, 38, 41, 255))
img.save(fname)
