#!/bin/bash

do_it() {
patterndo \
  "$HOME/downloads/torrents/complete" \
  '\[(.*)\] (.*) - (\d+(?:v\d+)?) \[.*\].mkv' \
  "$HOME"'/animes/$2/$2 $3 [$1].mkv' \
  backln
}

if [[ x"$1" = x"-v" ]]; then
    # do it verbosely
    do_it
else
    # do it more quietly
    do_it 2>/dev/null
fi
